# Generated by Django 5.1 on 2024-09-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='DOB',
            new_name='Dob',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Category',
        ),
        migrations.AddField(
            model_name='registration',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
