# Generated by Django 5.1 on 2024-09-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0002_rename_dob_staff_dob_remove_registration_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=10),
        ),
    ]
