# Generated by Django 5.1 on 2024-09-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0003_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
