# Generated by Django 5.1 on 2024-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_alter_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
