# Generated by Django 5.1 on 2024-09-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0005_registration_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='DOB',
            new_name='Dob',
        ),
    ]
