# Generated by Django 5.1 on 2024-09-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0006_rename_dob_doctors_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='DOB',
            new_name='Dob',
        ),
    ]
