# Generated by Django 5.1 on 2024-09-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0007_rename_staff_staffs_rename_dob_patients_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Token',
            field=models.IntegerField(default=1),
        ),
    ]
